### ISSUE TITLE
'Your login link has expired' on freshly generated login links

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/publishers#733]
> I'm trying to verify my email and when I receive the link. The Brave payments webpage says my account is already verified. Then when I try to login sometimes I don't receive the emails to log in and when I get them the Brave payments accounts says the link is already expired.

I've been experiencing this on development for a while now.

https://github.com/brave-intl/publishers/pull/440 is possibly related.

There could be a race condition somewhere in the process of sending an email where we aren't generating an `authentication_token` fast enough to be included in the email. 

cc @jenn-rhim

**Comment by nvonpentz** [comment]
It looks the spike in traffic caused problems for our server, and our app was unable to write to the database.  The app needs to write the auth token to the database for a user to log in.

@simplypsyke Please try again, it should work now.

**Comment by yachtcaptain23** [comment]
This is still happening. Worth revisiting #440 and seeing if there's a bug

**Comment by yachtcaptain23** [comment]
Unable to reproduce this now on staging and development.

Writing down all the possible causes and analysis on each cause given it's still a mystery:
- `UserAuthenticationToken` is a blocking call, so it's not a race condition there.
- Unlikely a possible time zone issues as production is set to PST.
